(function(){
'use strict';
const DATA_URL='data/data.json';
let data={}; let currentTab='events'; let activeCenter=0, activeSchool=0, eventFilter='Todos', search=''; let calDate=new Date(2026,9,1); let selectedDate='';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function init(){
 try{const r=await fetch(DATA_URL);data=await r.json();}catch(e){data=JSON.parse(localStorage.getItem('imagina2bit_data')||'{}');}
 const saved=localStorage.getItem('imagina2bit_data'); if(saved){try{data=Object.assign(data,JSON.parse(saved));}catch(e){}}
 renderAll(); bindGlobal();
}
function save(){localStorage.setItem('imagina2bit_data',JSON.stringify(data));}
function renderAll(){renderEvents();renderCenters();renderSchools();renderIndicators();renderNews();renderDocuments();renderCalendar();$('#year').textContent=new Date().getFullYear();renderMatrix();}
function bindGlobal(){
 $('#eventSearch').oninput=e=>{search=e.target.value.toLowerCase();renderTimeline()};
 $('#timelineTab').onclick=()=>{showView('timeline')}; $('#calendarTab').onclick=()=>{showView('calendar');renderCalendar()};
 $$('.modal-tabs button').forEach(b=>b.onclick=()=>{currentTab=b.dataset.tab;loadEditor()});
 $('#contactForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const body=`Nombre: ${f.get('nombre')}\n\n${f.get('mensaje')}`;location.href=`mailto:imagina2bit@puntosvuela.es?subject=${encodeURIComponent(f.get('asunto'))}&body=${encodeURIComponent(body)}`};
}
function showView(v){$('#timelineView').classList.toggle('hidden',v!=='timeline');$('#calendarView').classList.toggle('hidden',v!=='calendar');$('#timelineTab').classList.toggle('active',v==='timeline');$('#calendarTab').classList.toggle('active',v==='calendar');}
function renderEvents(){const locs=['Todos',...new Set(data.events.map(e=>e.lugar))];$('#locationFilters').innerHTML=locs.map(l=>`<button class="chip ${eventFilter===l?'active':''}" data-loc="${esc(l)}">${esc(l)}</button>`).join('');$$('[data-loc]').forEach(b=>b.onclick=()=>{eventFilter=b.dataset.loc;renderEvents();renderTimeline()});renderTimeline();}
function filteredEvents(){return data.events.filter(e=>(eventFilter==='Todos'||e.lugar===eventFilter)&&(!search||(`${e.evento} ${e.descripcion||''} ${e.audiencia||''} ${e.lugar}`).toLowerCase().includes(search))).sort((a,b)=>a.fecha.localeCompare(b.fecha));}
function renderTimeline(){const ev=filteredEvents();$('#timelineView').innerHTML=ev.length?`<div class="timeline">${ev.map(e=>`<article class="event"><div class="event-top"><span class="tag">${esc(e.categoria||'Actividad')}</span><span class="meta">${fmtDate(e.fecha)} · ${esc(e.horaInicio)}–${esc(e.horaFin)}</span></div><h3>${esc(e.evento)}</h3><div class="meta">📍 ${esc(e.lugar)} · ${esc(e.audiencia||'')}</div><p>${esc(e.descripcion||'')}</p></article>`).join('')}</div>`:`<div class="event">No hay actividades que coincidan con los filtros.</div>`;}
function fmtDate(s){return new Date(s+'T12:00:00').toLocaleDateString('es-ES',{day:'numeric',month:'long',year:'numeric'})}
function renderCalendar(){const y=calDate.getFullYear(),m=calDate.getMonth();const first=new Date(y,m,1);let start=(first.getDay()+6)%7;const days=new Date(y,m+1,0).getDate();let cells='';for(let i=0;i<start;i++)cells+='<div></div>';for(let d=1;d<=days;d++){const ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,ev=data.events.filter(e=>e.fecha===ds);cells+=`<button class="day ${ev.length?'has':''} ${selectedDate===ds?'selected':''}" data-date="${ds}"><strong>${d}</strong>${ev.slice(0,2).map(e=>`<span class="dot">${esc(e.evento)}</span>`).join('')}</button>`}$('#calendarView').innerHTML=`<div class="calendar"><div class="cal-head"><button class="chip" id="prevMonth">‹</button><h3>${new Date(y,m,1).toLocaleDateString('es-ES',{month:'long',year:'numeric'})}</h3><button class="chip" id="nextMonth">›</button></div><div class="cal-grid"><b>Lun</b><b>Mar</b><b>Mié</b><b>Jue</b><b>Vie</b><b>Sáb</b><b>Dom</b>${cells}</div></div><div class="calendar-details" id="calDetails"><h3>Selecciona un día</h3><p class="meta">Pulsa una fecha para ver sus actividades.</p></div>`;$('#prevMonth').onclick=()=>{calDate.setMonth(m-1);renderCalendar()};$('#nextMonth').onclick=()=>{calDate.setMonth(m+1);renderCalendar()};$$('.day').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;renderCalendar()});if(selectedDate){const ev=data.events.filter(e=>e.fecha===selectedDate);$('#calDetails').innerHTML=`<h3>${fmtDate(selectedDate)}</h3>${ev.length?ev.map(e=>`<div class="event"><b>${esc(e.horaInicio)}–${esc(e.horaFin)}</b><h3>${esc(e.evento)}</h3><div class="meta">${esc(e.lugar)}</div></div>`).join(''):'<p class="meta">No hay actividades este día.</p>'}`;}}
function renderCenters(){const c=data.puntosVuela[activeCenter];$('#centerTabs').innerHTML=data.puntosVuela.map((x,i)=>`<button class="${i===activeCenter?'active':''}" data-center="${i}">${esc(x.nombre)}</button>`).join('');$$('[data-center]').forEach(b=>b.onclick=()=>{activeCenter=+b.dataset.center;renderCenters()});$('#centerContent').innerHTML=`<div class="center-card"><div class="center-grid"><div><span class="eyebrow teal-bg">Punto Vuela</span><h2>${esc(c.nombre)}</h2><p>📍 ${esc(c.direccion)}, ${esc(c.codigoPostal)} · ${esc(c.municipio)}</p><img class="photo" src="${esc(c.fotoCentro)}" alt="${esc(c.nombre)}"><div class="info-list"><div class="info"><b>Teléfono</b><a href="tel:${esc(c.telefono)}">${esc(c.telefono)}</a></div><div class="info"><b>Email</b><a href="mailto:${esc(c.email)}">${esc(c.email)}</a></div><div class="info"><b>Horario</b>${esc(c.horario)}</div><div class="info"><b>Dirección</b>${esc(c.direccion)}</div></div></div><div><br><br><br><br><h3>Ubicación</h3><iframe class="map" loading="lazy" src="https://www.google.com/maps?q=${encodeURIComponent(c.mapQuery)}&output=embed"></iframe></div></div><div style="margin-top:28px;border-top:1px solid var(--border);padding-top:22px"><span class="eyebrow amber-bg">Equipo</span><h3>Agentes de Innovación Local</h3><div class="ail-grid">${c.ails.map(a=>`<article class="ail"><div class="ail-head"><img src="${esc(a.foto)}" alt="${esc(a.nombre)}"><div><h4>${esc(a.nombre)}</h4><p>${esc(a.cargo)}</p></div></div><p>☎ <a href="tel:${esc(a.telefono)}">${esc(a.telefono)}</a></p><p>✉ <a href="mailto:${esc(a.email)}">${esc(a.email)}</a></p></article>`).join('')}</div></div></div>`;}
function renderSchools(){const s=data.schools[activeSchool];$('#schoolTabs').innerHTML=data.schools.map((x,i)=>`<button class="${i===activeSchool?'active':''}" data-school="${i}">${esc(x.nombre)}</button>`).join('');$$('[data-school]').forEach(b=>b.onclick=()=>{activeSchool=+b.dataset.school;renderSchools()});$('#schoolContent').innerHTML=`<div class="school-card"><div class="school-grid"><div><span class="eyebrow green-bg">Centro educativo</span><h3>${esc(s.nombre)}</h3><p><b>${esc(s.direccion)}</b><br>${esc(s.municipio)}</p><img class="photo" src="${esc(s.fotoCentro)}" alt="${esc(s.nombre)}"><p>${esc(s.descripcion)}</p><span class="tag">${esc(s.etapaEducativa)}</span></div><div><br><br><br><br><h3>Mapa</h3><iframe class="map" loading="lazy" src="https://www.google.com/maps?q=${encodeURIComponent(s.mapQuery)}&output=embed"></iframe><div class="contact-box"><b>Participación en iMagina2:Bit</b><span>Programación, robótica educativa, pensamiento computacional y retos intercentros.</span></div></div></div></div>`;}
function renderIndicators(){const colors={emerald:'#d1fae5',amber:'#fef3c7',sky:'#e0f2fe',purple:'#f3e8ff'};$('#indicatorsGrid').innerHTML=data.indicators.map(i=>`<article class="indicator" style="background:${colors[i.color]||'#f3e8ff'}"><span class="tag">${esc(i.icono)}</span><b>${esc(i.valor)}</b><h3>${esc(i.etiqueta)}</h3><p>${esc(i.descripcion)}</p></article>`).join('');}
function renderNews(){$('#newsList').innerHTML=data.entries.map(n=>`<article class="news"><img src="${esc(n.foto)}" alt=""><div class="news-main"><div class="meta">${esc(n.fecha)} · ${esc(n.categoria||'Actualidad')} · ${esc(n.autor||'')}</div><h3>${esc(n.titulo)}</h3><p>${esc(n.descripcion)}</p></div></article>`).join('');}
function renderDocuments(){$('#documentsList').innerHTML=data.documents.map(d=>`<article class="document"><div class="file-badge">${esc(d.formato)}</div><div class="document-main"><div class="meta">${esc(d.fecha)} · ${esc(d.tamanio)}</div><h3>${esc(d.titulo)}</h3><p>${esc(d.descripcion)}</p></div><a class="btn ${d.accion==='editar'?'btn-purple':'btn-light'} small" href="${esc(d.url)}">${d.accion==='editar'?'Editar':'Descargar'}</a></article>`).join('');}
const presets={heart:[0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,0,0,1,0,0],smile:[0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,1,1,1,0],robot:[1,1,0,1,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,1,0,0,0,1],bit:[1,1,1,0,0,1,0,1,0,0,1,1,1,0,1,1,0,1,0,1,1,1,1,0,1]};let leds=presets.heart.slice();let preset='heart';
function renderMatrix(){$('#matrix').innerHTML=leds.map((on,i)=>`<button class="led ${on?'on':''}" data-led="${i}" aria-label="LED ${i+1}"></button>`).join('');$$('[data-led]').forEach(b=>b.onclick=()=>{leds[+b.dataset.led]=!leds[+b.dataset.led];preset='';renderMatrix();});$$('[data-preset]').forEach(b=>{b.classList.toggle('active',b.dataset.preset===preset);b.onclick=()=>{preset=b.dataset.preset;leds=presets[preset].slice();renderMatrix()}})}
function openModal(tab){currentTab=tab||'events';$('#jsonModal').classList.remove('hidden');loadEditor();}
function closeModal(){$('#jsonModal').classList.add('hidden');}
function loadEditor(){$$('.modal-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===currentTab));$('#jsonEditor').value=JSON.stringify(data[currentTab],null,2);$('#jsonError').classList.add('hidden');$('#jsonOk').classList.add('hidden');}
function applyJson(){try{const parsed=JSON.parse($('#jsonEditor').value);if(!Array.isArray(parsed))throw Error('El JSON debe contener un array.');data[currentTab]=parsed;save();renderAll();$('#jsonOk').classList.remove('hidden');$('#jsonError').classList.add('hidden');}catch(e){$('#jsonError').textContent='JSON no válido: '+e.message;$('#jsonError').classList.remove('hidden');$('#jsonOk').classList.add('hidden');}}
async function copyJson(){try{await navigator.clipboard.writeText($('#jsonEditor').value);alert('JSON copiado al portapapeles.')}catch(e){alert('No se pudo copiar automáticamente.')}}
function downloadJson(){const blob=new Blob([$('#jsonEditor').value],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`imagina2bit-${currentTab}.json`;a.click();URL.revokeObjectURL(a.href)}
async function resetData(){if(!confirm('¿Restablecer todos los datos iniciales?'))return;localStorage.removeItem('imagina2bit_data');try{const r=await fetch(DATA_URL+'?t='+Date.now());data=await r.json();renderAll();loadEditor();}catch(e){alert('No se pudo recargar data.json.')}}
init();
})();
